import { BrowserRouter, Routes, Route, Navigate, useLocation } from "react-router-dom"
import { AuthProvider, useAuth } from "@/contexts/AuthContext"

import { SystemProvider } from "@/contexts/SystemContext"
import { DashboardLayout } from "@/components/layout/DashboardLayout"
import { Dashboard } from "@/core/dashboard/Dashboard"
import { AuthLayout } from "@/components/layout/AuthLayout"
import { Login } from "@/core/authentication/Login"
import { Register } from "@/core/authentication/Register"
import { ForgotPassword } from "@/core/authentication/ForgotPassword"
import { ComingSoon } from "@/pages/error/ComingSoon"
import { Error404 } from "@/pages/error/Error404"
import { Providers as AIProviders } from "@/core/ai/Providers"
import { DataTableDemo } from "@/pages/components/DataTableDemo"
import { Plans } from "@/core/subscription/Plans"
import { Invoices } from "@/core/subscription/Invoices"
import { Coupons } from "@/core/subscription/Coupons"
import { UsageLimits } from "@/core/subscription/UsageLimits"
import { SettingsLayout } from "@/core/settings/SettingsLayout"

import { Companies } from "@/core/tenant/Companies"
import { UsersList } from "@/core/users/UsersList"
import { RolesList } from "@/core/roles/RolesList"
import { UserActivityTimeline } from "@/core/users/UserManagementPages"
import { Departments } from "@/core/organization/Departments"
import { Teams } from "@/core/organization/Teams"
import { Analytics } from "@/core/reports/Analytics"
import { NotificationLogs } from "@/core/notifications/NotificationLogs"
import { MediaLibrary } from "@/core/storage/MediaLibrary"
import { Files } from "@/core/storage/Files"
import { AuditLogs } from "@/core/system/AuditLogs"
import { Authentication } from "@/core/authentication/Authentication"
import { Organizations } from "@/core/organization/Organizations"
import { Features } from "@/core/subscription/Features"
import { SuperAdminDashboard } from "@/core/superadmin/SuperAdminDashboard"
import { AITokens } from "@/core/ai/AITokens"
import { AILogs } from "@/core/ai/AILogs"
import { EmailTemplates } from "@/core/notifications/EmailTemplates"
import { LoginLogs } from "@/core/system/LoginLogs"
import { APILogs } from "@/core/system/APILogs"
import { ErrorLogs } from "@/core/system/ErrorLogs"
import { AITemplates } from "@/core/ai/AITemplates"
import { AISettings } from "@/core/ai/AISettings"
import { SMSTemplates } from "@/core/notifications/SMSTemplates"
import { WhatsAppTemplates } from "@/core/notifications/WhatsAppTemplates"
import { 
  BillingOverview, Transactions, 
  ExportsCenter, 
  UIComponents 
} from "@/shared/AutoGeneratedPages"
import { ScheduledReports } from "@/core/reports/ScheduledReports"
import { FormBuilder } from "@/core/builders/FormBuilder"
import { Sessions } from "@/core/authentication/Sessions"
import { Devices } from "@/core/authentication/Devices"
import { Branches } from "@/core/organization/Branches"
import { Domains } from "@/core/tenant/Domains"
import { Branding } from "@/core/tenant/Branding"
import { Permissions } from "@/core/permissions/Permissions"
import { Channels } from "@/core/notifications/Channels"
import { Workflows } from "@/core/workflow/Workflows"
import { Automations } from "@/core/workflow/Automations"
import { APIKeys } from "@/core/api/APIKeys"
import { Webhooks } from "@/core/api/Webhooks"
import { KnowledgeBase } from "@/core/ai/KnowledgeBase"

function ProtectedRoute({ children }) {
  const { isAuthenticated } = useAuth()
  const location = useLocation()

  if (!isAuthenticated) {
    return <Navigate to="/login" state={{ from: location }} replace />
  }

  return children
}

function App() {
  return (
    <AuthProvider>
        <SystemProvider>
          <BrowserRouter>
          <Routes>
        {/* Auth Routes */}
        <Route element={<AuthLayout />}>
          <Route path="/login" element={<Login />} />
          <Route path="/register" element={<Register />} />
          <Route path="/forgot-password" element={<ForgotPassword />} />
        </Route>

        {/* Dashboard Routes (Protected) */}
        <Route element={
          <ProtectedRoute>
            <DashboardLayout />
          </ProtectedRoute>
        }>
          <Route path="/dashboard" element={<Dashboard />} />
          <Route path="/" element={<Navigate to="/dashboard" replace />} />
          
          {/* Billing & Subscription Module */}
          <Route path="/subscription/billing" element={<BillingOverview />} />
          <Route path="/subscription/plans" element={<Plans />} />
          <Route path="/subscription/features" element={<Features />} />
          <Route path="/subscription/invoices" element={<Invoices />} />
          <Route path="/subscription/coupons" element={<Coupons />} />
          <Route path="/subscription/usage" element={<UsageLimits />} />
          <Route path="/subscription/transactions" element={<Transactions />} />

          {/* User Management & Tenants */}
          <Route path="/organization" element={<Organizations />} />
          <Route path="/organization/branches" element={<Branches />} />
          <Route path="/organization/departments" element={<Departments />} />
          <Route path="/organization/teams" element={<Teams />} />
          <Route path="/multitenant/tenants" element={<Companies />} />
          <Route path="/multitenant/domains" element={<Domains />} />
          <Route path="/multitenant/branding" element={<Branding />} />

          {/* Access Control */}
          <Route path="/access/users" element={<UsersList />} />
          <Route path="/access/roles" element={<RolesList />} />
          <Route path="/access/permissions" element={<Permissions />} />

          {/* Identity */}
          <Route path="/identity/auth" element={<Authentication />} />
          <Route path="/identity/sessions" element={<Sessions />} />
          <Route path="/identity/devices" element={<Devices />} />
          <Route path="/identity/logins" element={<LoginLogs />} />

          {/* Reports & Analytics */}
          <Route path="/analytics" element={<Analytics />} />
          <Route path="/reports/builder" element={<ScheduledReports />} />
          <Route path="/reports/exports" element={<ExportsCenter />} />

          {/* Notifications & Storage */}
          <Route path="/notifications/logs" element={<NotificationLogs />} />
          <Route path="/notifications/channels" element={<Channels />} />
          <Route path="/notifications/email-templates" element={<EmailTemplates />} />
          <Route path="/notifications/sms-templates" element={<SMSTemplates />} />
          <Route path="/notifications/whatsapp-templates" element={<WhatsAppTemplates />} />
          <Route path="/storage/files" element={<Files />} />
          <Route path="/storage/media" element={<MediaLibrary />} />

          {/* Workflow & API */}
          <Route path="/workflow/automations" element={<Automations />} />
          <Route path="/workflow/builder" element={<Workflows />} />
          <Route path="/api/keys" element={<APIKeys />} />
          <Route path="/api/webhooks" element={<Webhooks />} />

          {/* AI Module */}
          <Route path="/ai/providers" element={<AIProviders />} />
          <Route path="/ai/templates" element={<AITemplates />} />
          <Route path="/ai/knowledge" element={<KnowledgeBase />} />
          <Route path="/ai/logs" element={<AILogs />} />

          {/* Settings Module */}
          <Route path="/settings" element={<SettingsLayout />} />

          {/* Builders & Components Module */}
          <Route path="/builders/dashboard" element={<UIComponents />} />
          <Route path="/builders/form" element={<FormBuilder />} />
          
          {/* System */}
          <Route path="/superadmin" element={<SuperAdminDashboard />} />
          <Route path="/system/audit" element={<AuditLogs />} />
          <Route path="/system/activity" element={<UserActivityTimeline />} />
          <Route path="/system/monitoring" element={<ErrorLogs />} />

          {/* Error States */}
          <Route path="/404" element={<Error404 />} />
          <Route path="/403" element={<Error404 />} />
          <Route path="/500" element={<Error404 />} />
          
          {/* Catch-all for unbuilt modules mapped in Sidebar */}
          <Route path="*" element={<ComingSoon moduleName="Requested" />} />
        </Route>
          </Routes>
          </BrowserRouter>
      </SystemProvider>
    </AuthProvider>
  )
}

export default App
